# Permalinks
permalink:      /:day-:month-:year/:title

# Setup
title:          Escobar
paginate:       5
baseurl:        "/"
url:            "https://blog.escobar.eu.org"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Daniel Escobar
  url:          https://escobar.eu.org
  email:        info@escobar.eu.org

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
